import React from "react"

export const DataStaff =[
  {
    "id": 8,
    "userId": "LĐpoanh",
    "firstName": "La",
    "lastName": "Đinh Văn",
    "birthDay": "10-08-2001",
    "email": "poanh@gmail.com",
    "phone": "0363755300",
    "address": "Phú Lộc",
    "imageLink": "44f185f4-4633-478a-a505-6dae187d9494--girl.jpeg",
    "password": "$2a$10$as8eQKO25VdrBg1ivqQ8EeHftY2nDIAwCZhSJOrJ0STF/MyKuXpo2",
    "knowledge": "Tốt nghiệp cử nhân Y, Tiếng anh y khoa",
    "isDisable": false,
    "hospitalId": "BVMPA7655",
    "wardId": "1",
    "roleId": 5,
    "information": "Việc làm của các bác sĩ chẩn đoán và điều trị bệnh tật và chấn thương. Họ lấy lịch sử sức khỏe của bệnh nhân, kiểm tra các vùng cơ thể cảm thấy không khỏe hoặc đau đớn, và giải thích các xét nghiệm chẩn đoán, và lên kế hoạch và thực hiện các khóa điều trị.",
    "imageUrl": "https://storage-vnportal.vnpt.vn/bvdkbd/1/BacSy/bi9t0069_copy.jpg"
  },
  {
    "id": 9,
    "userId": "TBphamvanoanh",
    "firstName": "Tiến",
    "lastName": "Bùi Công",
    "birthDay": "10-08-2001",
    "email": "phamvanoanh@gmail.com",
    "phone": "0123456789",
    "address": "Hương Trà",
    "imageLink": "44f185f4-4633-478a-a505-6dae187d9494--girl.jpeg",
    "password": "$2a$10$0HdH11AKA5b/yGwRRNoESO9l40J7L6gRB7EIDL4j.yQSiO17y6vo.",
    "knowledge": "Bằng bác sĩ y học cổ truyền,Bằng bác sĩ nha khoa,Bằng bác sĩ y khoa",
    "isDisable": false,
    "hospitalId": "BVMPA7655",
    "wardId": "2",
    "roleId": 5,
    "information": "Việc làm của các bác sĩ chẩn đoán và điều trị bệnh tật và chấn thương. Họ lấy lịch sử sức khỏe của bệnh nhân, kiểm tra các vùng cơ thể cảm thấy không khỏe hoặc đau đớn, và giải thích các xét nghiệm chẩn đoán, và lên kế hoạch và thực hiện các khóa điều trị.",
    "imageUrl": "https://storage-vnportal.vnpt.vn/bvdkbd/1/BacSy/bi9t0069_copy.jpg"
  },
  {
    "id": 10,
    "userId": "Nv1",
    "firstName": "Tiến1",
    "lastName": "Nguyễn Văn",
    "birthDay": "10-08-2001",
    "email": "bs1@gmail.com",
    "phone": "0123456789",
    "address": "Hương Trà",
    "imageLink": "44f185f4-4633-478a-a505-6dae187d9494--girl.jpeg",
    "password": "$2a$10$0HdH11AKA5b/yGwRRNoESO9l40J7L6gRB7EIDL4j.yQSiO17y6vo.",
    "knowledge": "Bằng bác sĩ y học cổ truyền,Bằng bác sĩ nha khoa,Bằng bác sĩ y khoa",
    "isDisable": false,
    "hospitalId": "BVPLH9287",
    "wardId": "2",
    "roleId": 5,
    "information": "Việc làm của các bác sĩ chẩn đoán và điều trị bệnh tật và chấn thương. Họ lấy lịch sử sức khỏe của bệnh nhân, kiểm tra các vùng cơ thể cảm thấy không khỏe hoặc đau đớn, và giải thích các xét nghiệm chẩn đoán, và lên kế hoạch và thực hiện các khóa điều trị.",
    "imageUrl": "https://storage-vnportal.vnpt.vn/bvdkbd/1/BacSy/bi9t0069_copy.jpg"
  },
  {
    "id": 11,
    "userId": "Nv2",
    "firstName": "Tiến2",
    "lastName": "La Thị",
    "birthDay": "10-08-2001",
    "email": "bs2@gmail.com",
    "phone": "0123456789",
    "address": "Hương Trà",
    "imageLink": "44f185f4-4633-478a-a505-6dae187d9494--girl.jpeg",
    "password": "$2a$10$0HdH11AKA5b/yGwRRNoESO9l40J7L6gRB7EIDL4j.yQSiO17y6vo.",
    "knowledge": "Bằng bác sĩ y học cổ truyền,Bằng bác sĩ nha khoa,Bằng bác sĩ y khoa",
    "isDisable": false,
    "hospitalId": "BVPLH9287",
    "wardId": "2",
    "roleId": 5,
    "information": "Việc làm của các bác sĩ chẩn đoán và điều trị bệnh tật và chấn thương. Họ lấy lịch sử sức khỏe của bệnh nhân, kiểm tra các vùng cơ thể cảm thấy không khỏe hoặc đau đớn, và giải thích các xét nghiệm chẩn đoán, và lên kế hoạch và thực hiện các khóa điều trị.",
    "imageUrl": "https://storage-vnportal.vnpt.vn/bvdkbd/1/BacSy/bi9t0069_copy.jpg"
  },
  {
    "id": 12,
    "userId": "Nv3",
    "firstName": "Nga",
    "lastName": "Lê Thị",
    "birthDay": "10-08-2001",
    "email": "bs3@gmail.com",
    "phone": "0123456789",
    "address": "Hương Trà",
    "imageLink": "44f185f4-4633-478a-a505-6dae187d9494--girl.jpeg",
    "password": "$2a$10$0HdH11AKA5b/yGwRRNoESO9l40J7L6gRB7EIDL4j.yQSiO17y6vo.",
    "knowledge": "Bằng bác sĩ y học cổ truyền,Bằng bác sĩ nha khoa,Bằng bác sĩ y khoa",
    "isDisable": false,
    "hospitalId": "BVMPB8232",
    "wardId": "2",
    "roleId": 5,
    "information": "Việc làm của các bác sĩ chẩn đoán và điều trị bệnh tật và chấn thương. Họ lấy lịch sử sức khỏe của bệnh nhân, kiểm tra các vùng cơ thể cảm thấy không khỏe hoặc đau đớn, và giải thích các xét nghiệm chẩn đoán, và lên kế hoạch và thực hiện các khóa điều trị.",
    "imageUrl": "https://storage-vnportal.vnpt.vn/bvdkbd/1/BacSy/bi9t0069_copy.jpg"
  },
  {
    "id": 13,
    "userId": "Nv4",
    "firstName": "Hùng",
    "lastName": "Trần Văn",
    "birthDay": "10-08-2001",
    "email": "bs4@gmail.com",
    "phone": "0123456789",
    "address": "Hương Trà",
    "imageLink": "44f185f4-4633-478a-a505-6dae187d9494--girl.jpeg",
    "password": "$2a$10$0HdH11AKA5b/yGwRRNoESO9l40J7L6gRB7EIDL4j.yQSiO17y6vo.",
    "knowledge": "Bằng bác sĩ y học cổ truyền,Bằng bác sĩ nha khoa,Bằng bác sĩ y khoa",
    "isDisable": false,
    "hospitalId": "BVMPB8232",
    "wardId": "2",
    "roleId": 5,
    "information": "Việc làm của các bác sĩ chẩn đoán và điều trị bệnh tật và chấn thương. Họ lấy lịch sử sức khỏe của bệnh nhân, kiểm tra các vùng cơ thể cảm thấy không khỏe hoặc đau đớn, và giải thích các xét nghiệm chẩn đoán, và lên kế hoạch và thực hiện các khóa điều trị.",
    "imageUrl": "https://storage-vnportal.vnpt.vn/bvdkbd/1/BacSy/bi9t0069_copy.jpg"
  },
  {
    "id": 14,
    "userId": "Nv5",
    "firstName": "Đạt",
    "lastName": "Ông Ho",
    "birthDay": "10-08-2001",
    "email": "bs5@gmail.com",
    "phone": "0123456789",
    "address": "Hương Trà",
    "imageLink": "44f185f4-4633-478a-a505-6dae187d9494--girl.jpeg",
    "password": "$2a$10$0HdH11AKA5b/yGwRRNoESO9l40J7L6gRB7EIDL4j.yQSiO17y6vo.",
    "knowledge": "Bằng bác sĩ y học cổ truyền,Bằng bác sĩ nha khoa,Bằng bác sĩ y khoa",
    "isDisable": false,
    "hospitalId": "BVMPB8232",
    "wardId": "2",
    "roleId": 5,
    "information": "Việc làm của các bác sĩ chẩn đoán và điều trị bệnh tật và chấn thương. Họ lấy lịch sử sức khỏe của bệnh nhân, kiểm tra các vùng cơ thể cảm thấy không khỏe hoặc đau đớn, và giải thích các xét nghiệm chẩn đoán, và lên kế hoạch và thực hiện các khóa điều trị.",
    "imageUrl": "https://storage-vnportal.vnpt.vn/bvdkbd/1/BacSy/bi9t0069_copy.jpg"
  }
 ]